---
- name: update apt cache
  apt:
    update_cache: yes
- name: install git
  apt:
    name: git
    state: present
- name: clone repo
  git:
    repo: "{{ repo_url }}"
    dest: "{{ repo_clone_path }}"
    version: main
    force: yes
  
