---
- name: update and upgrade system packages
  apt:
    update_cache: yes
    upgrade: dist

- name: add deadsnakes PPA repository
  apt_repository:
    repo: ppa:deadsnakes/ppa
    state: present

- name: update package cache after adding PPA
  apt:
    update_cache: yes

- name: install python 3.12
  apt:
    name: python3.12
    state: present

- name: configure python3.12 as default python3 alternative
  command: "update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.12 1"

- name: replace apt_pkg module
  copy:
    remote_src: yes
    src: /usr/lib/python3/dist-packages/apt_pkg.cpython-38-x86_64-linux-gnu.so
    dest: /usr/lib/python3/dist-packages/apt_pkg.so
