---
- name: start nginx
  hosts: web
  become: yes
  roles:
    - nginx

- name: start app using docker
  hosts: app
  become: yes
  roles:
    - docker
  tasks:
    - name: install docker sdk
      pip:
        name: docker

    - name: run app in docker container
      docker_container:
        name: django-app
        image: timurbabs/django:latest
        state: started
        restart_policy: always
        ports:
          - "8000:8000"
    
    - name: check if app running
      uri:
        url: "http://{{ nginx_host }}/"
        status_code: 200
        return_content: yes
