roles:
  - src: git+https://gitlab.com/ansible_roles9964801/docker.git
    version: main
    name: docker
  
  - src: git+https://gitlab.com/ansible_roles9964801/nginx.git
    version: main
    name: nginx
