---
- name: install dependencies
  apt:
    state: latest     
    update_cache: yes
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
- name: add GPG key
  apt_key:
     url: https://download.docker.com/linux/ubuntu/gpg
     state: present
- name: add docker repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present
- name: install docker
  apt:
    state: latest
    update_cache: yes
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
- name: check docker is active
  service:
    name: docker
    state: started
    enabled: yes
- name: check docker group exists
  ansible.builtin.group:
    name: docker
    state: present
